// Generated by 'cmm'.
// Publicly accessible module functions and attributes.
#ifndef github_com_ricallinson_testlib_math
#define github_com_ricallinson_testlib_math
int MathNext();
int MathIncrement(int x);
#endif
