// Generated by 'cmm'.
// Publicly accessible module functions and attributes.
#ifndef github_com_ricallinson_testmap_map
#define github_com_ricallinson_testmap_map
typedef struct MapItem {
    char *key;
    char *value;
    struct MapItem *next;
    struct MapItem *prev;
} MapItem;
typedef struct {
    struct MapItem *first;
    struct MapItem *last;
    long length;
} Map;
Map *MapStringCreate();
int MapStringFree(Map *map);
char *MapStringGet(Map *map, char *key);
void MapStringPut(Map *map, char *key, char *value);
#endif
