// Generated by 'cmm'.
// Publicly accessible.
#ifndef github_com_ricallinson_teststruct_account
#define github_com_ricallinson_teststruct_account
typedef struct {
    int id;
    int firstname;
    int lastname;
} Account;
Account AccountCreate(int firstname, int lastname);
#endif
