// Generated by 'cmm'.
// Publicly accessible module functions and attributes.
#ifndef github_com_ricallinson_teststruct_account
#define github_com_ricallinson_teststruct_account
typedef struct {
    int id;
    char *firstname;
    char *lastname;
} Account;
Account AccountCreate(char *firstname, char *lastname);
void AccountToString(Account *account, char *s);
char *AccountToChars(Account *account);
#endif
